### ISSUE TITLE
Registering as official plug in

### ISSUE THREAD

**Issue by a10kiloham** [HeavenVolkoff/caddy-authelia#2]
I just discovered this. Looks awesome. Would you mind registering it w caddy as an official plug-in? I'm sure many others would love it.
Thanks!

**Comment by HeavenVolkoff** [comment]
Hey, thanks for the interest in this project.

I just registered the plugin:
https://caddyserver.com/docs/modules/http.handlers.authelia
You can also find it in Caddy's download page:
https://caddyserver.com/download

**Comment by a10kiloham** [comment]
awesome thanks!
